describe("Home ViewTo Log View", () => {
  it("Visit the Home Page", () => {
    cy.visit("http://localhost:8080")
    cy.get("h1").should("contain.text", "Page | Accueil")
    cy.contains("Nos produits").click()
    cy.url().should("include", "#menu")
    cy.pause()
    cy.contains("Connexion").click()
    //cy.url().should('include', '#menu')

    cy.get("#email").type("sarah@gmail.com")
    cy.get("#password").type("caroline")
    cy.get("#submit-button").click()
    cy.url().should("include", "#dashboard")
    cy.pause()
    cy.get("#logout-button").click()
    cy.contains("Connexion").click()
    cy.contains("ici").click()
    cy.get("#email").type("alex@gmail.com")
    cy.get("#password").type("ludivine")
    cy.get("#confirmed-password").type("ludivine")
    cy.get("#submit-button").click()
    cy.url().should("include", "#dashboard")
    cy.pause()
    cy.get("#logout-button").trigger("mousedown")
  })
})
